spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  application:
    name: stats
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
